export const Users = [
    {
      id:1,
      profilePicture: "https://www.indiafilings.com/learn/wp-content/uploads/2023/03/Can-a-single-person-own-a-firm-in-India.jpg",
      username: "Safak Kocaoglu",
    },
    {
      id:2,
      profilePicture: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
      username: "Janell Shrum",
    },
    {
      id:3,
      profilePicture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLA994hpL3PMmq0scCuWOu0LGsjef49dyXVg&usqp=CAU",
      username: "Alex Durden",
    },
    {
      id:4,
      profilePicture: "https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?cs=srgb&dl=pexels-simon-robben-614810.jpg&fm=jpg",
      username: "Dora Hawks",
    },
    {
      id:5,
      profilePicture: "https://image.cnbcfm.com/api/v1/image/107241090-1684160036619-gettyimages-1255019394-AFP_33F44YL.jpeg?v=1685596344&w=740&h=416&ffmt=webp&vtcrop=y",
      username: "Thomas Holden",
    },
    {
      id:6,
      profilePicture: "https://www.newvisiontheatres.com/wp-content/uploads/2023/06/Dwayne-Johnson.jpg",
      username: "Shirley Beauchamp",
    },
    {
      id:7,
      profilePicture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcShh3-eBB9rvaPIHYCx8ggPDBB17xfrj-KytA&usqp=CAU",
      username: "Travis Bennett",
    },
    {
      id:8,
      profilePicture: "https://toppng.com/uploads/preview/person-png-11553989513mzkt4ocbrv.png",
      username: "Kristen Thomas",
    },
    {
      id:9,
      profilePicture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxD6noTj3HS0JY0sN2sU2EU5uya669lbP6lQ&usqp=CAU",
      username: "Gary Duty",
    },
    {
      id:10,
      profilePicture: "https://www.thenews.com.pk/assets/uploads/updates/2023-06-06/1077624_9529706_Oppenheimer_updates.jpg",
      username: "Safak Kocaoglu",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "https://img.freepik.com/free-photo/luxury-car-speeds-by-modern-building-dusk-generative-ai_188544-8048.jpg?size=626&ext=jpg&ga=GA1.1.1413502914.1696550400&semt=ais",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "https://hips.hearstapps.com/hmg-prod/images/2024-lamborghini-revuelto-127-641a1d518802b.jpg?crop=0.813xw:0.721xh;0.0994xw,0.128xh&resize=1200:*",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "https://media.wired.com/photos/63b8d0a771c6b526845f15a6/4:3/w_2400,h_1800,c_limit/CES-2023-PEUGEOT_INCEPTION_CONCEPT_2301CN202.jpg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "https://www.autocar.co.uk/sites/autocar.co.uk/files/styles/gallery_slide/public/images/car-reviews/first-drives/legacy/rolls_royce_phantom_top_10.jpg?itok=XjL9f1tx",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "https://img.freepik.com/premium-photo/remarkable-landscape-colorful-autumn-wanaka-lake-with-sunrise-fresh-morning-ai-image_966797-64.jpg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "https://img.freepik.com/premium-photo/relaxing-place-national-5a-scenic-spot-green-mountain-clean-green-freshwater-lake-natural-scenery_327903-961512.jpg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "https://images.unsplash.com/photo-1596570630094-43ddbe073a77?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8bmF0dXJhbCUyMHNjZW5lcnl8ZW58MHx8MHx8fDA%3D&w=1000&q=80",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "https://picjumbo.com/wp-content/uploads/beautiful-nature-scenery-smartphone-wallpaper-free-photo-2210x3943.jpg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "https://w0.peakpx.com/wallpaper/42/267/HD-wallpaper-nature-scenery-scenery-nature.jpg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "https://c4.wallpaperflare.com/wallpaper/352/191/690/beautiful-nature-scenery-green-trees-lake-river-mountains-clouds-wallpaper-preview.jpg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];